version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080" # main web interface
    extra_hosts:
      host.docker.internal: host-gateway # For Linux
    volumes:
      - ".:/app"
    command: yarn dev
